name: CI workflow

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_iOS:
    name: Build and Test project on iOS
    runs-on: [ self-hosted, iOS ]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v6
      - name: Build
        run: xcodebuild -scheme VersionChecker-Package build -sdk iphonesimulator -destination "generic/platform=iOS"
      - name: Test
        run: xcodebuild -scheme VersionChecker-Package test -destination "platform=iOS Simulator,name=iPhone 17,OS=latest"
